In [1]:
import numpy as np
arr=np.array([2,1,3,5,7,6,8,4])
print(arr)
np.sort(arr)

[2 1 3 5 7 6 8 4]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
import numpy as np
x=np.array([3,1,2])
np.argsort(x)


array([1, 2, 0])

In [9]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.concatenate((a,b),axis=0)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a=np.arange(6)
print(a)
b=a.reshape(3,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [17]:
data=np.array([1,2,3])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2])

2
[1 2]
[2 3]
2


In [19]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[a<5])
five_up=(a>=5)
print(five_up)
print(a[five_up])
divisible_by_2=a[a%2==0]
print(divisible_by_2)
c=a[(a>2)&(a<11)]
print(c)
five_up=(a>5)|(a==5)
print(five_up)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [20]:
data=np.array([1.0,2.0])
data*1.6

array([1.6, 3.2])

In [21]:
import numpy as np
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])