In [6]:
import numpy as np
yields=np.array([
    [45,48,52,49,53],
    [38,41,39,44,42],
    [52,55,58,56,60],
    [41,43,45,47,46]
])
weather_factors=np.array([1.0,0.95,1.05,0.98,1.02])
print('original yields(tons/hectare):')
print(yields)
print('\n weather impact factors:',weather_factors)
adjusted_yields=yields*weather_factors
print('\n weather_adjusted yields:')
print(adjusted_yields.round(2))
exceptional=adjusted_yields>55
print('\nexceptional yields(>55):')
print(adjusted_yields[exceptional])
categories=np.where(
    adjusted_yields>50,'high',
    np.where(adjusted_yields>40,'medium','low')
)
print('\nyield categories:')
print(categories)
selected_farms=[0,2]
print('\nselected farm yields:')
print(yields[selected_farms])
good_years=adjusted_yields[(adjusted_yields>45)&(adjusted_yields<55)]
print(f'\ngood performing years(45-55 tons):')
print(good_years)


original yields(tons/hectare):
[[45 48 52 49 53]
 [38 41 39 44 42]
 [52 55 58 56 60]
 [41 43 45 47 46]]

 weather impact factors: [1.   0.95 1.05 0.98 1.02]

 weather_adjusted yields:
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

exceptional yields(>55):
[60.9 61.2]

yield categories:
[['medium' 'medium' 'high' 'medium' 'high']
 ['low' 'low' 'medium' 'medium' 'medium']
 ['high' 'high' 'high' 'high' 'high']
 ['medium' 'medium' 'medium' 'medium' 'medium']]

selected farm yields:
[[45 48 52 49 53]
 [52 55 58 56 60]]

good performing years(45-55 tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]


In [28]:
import numpy as np
a=np.arange(50).reshape(10,5)
print('original array(10*5):\n',a)
print('\n',a[:])
print('\n',a[3,:])
print('\n',a[:,-1])
print('\n',a[:,1])
selected_rows=a[a[:,0]>20]
print('\nrows where first feature>20:\n',selected_rows)

original array(10*5):
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]

 [15 16 17 18 19]

 [ 4  9 14 19 24 29 34 39 44 49]

 [ 1  6 11 16 21 26 31 36 41 46]

rows where first feature>20:
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
