In [7]:
import numpy as np
import pandas as pd
ser=pd.Series([1,2,3,4,5])
arr=np.array(ser)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(42)
print(arr)
print(arr.ndim)

42
0


In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=6)
print(arr)
print('number of dimensions:',arr.ndim)

[[[[[[1 2 3 4]]]]]]
number of dimensions: 6


In [ ]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr_2d=np.array([[1,2,3],[4,5,6]])
zeros=np.zeros((3,4))
ones=np.ones((2,3))
range_arr=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identity=np.eye(3)
random_arr=np.random.rand(3,4)
print(zeros)
print(ones)
print(range_arr)
print(linspace)
print(identity)
print(random_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.07227868 0.94845816 0.20376325 0.34111779]
 [0.75213504 0.5926621  0.32625855 0.88922861]
 [0.31246037 0.3605162  0.41797958 0.50358376]]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
print(a.dtype)
print(a.size)
print(a.ndim)
print(np.sum(a))

int64
6
2
21


In [ ]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
print(np.max(a))
print(np.min(a))

6
1


In [ ]:
b=np.array([10,40,30])
np.argmax(b)


np.int64(1)

In [3]:
#crop yields of 4 farms in 5 season
import numpy as np
crop_yields=np.array([
    [12.5,13.2,14.1,13.8,15.2],
    [10.3,11.5,10.8,12.1,11.9],
    [15.1,14.8,16.2,15.5,16.8],
    [11.2,10.9,12.3,11.7,12.8]
])
print('crop yiels array(tons):')
print(crop_yields)
print(f'\nshape:{crop_yields.dtype}')
print(f'data type:{crop_yields.dtype}')
print(f'total elements:{crop_yields.size}')
print(f'number of dimensions:{crop_yields.ndim}')
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)
print(f'\nTotal production:{total_yield}tons')
print(f'average per farm:{avg_yield_per_farm}tons')
print(f'average per season:{avg_yield_per_season}tons')
print(f'maximum yield:{max_yield}tons')
print(f'minimum yield:{min_yield}tons')

crop yiels array(tons):
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

shape:float64
data type:float64
total elements:20
number of dimensions:2

Total production:262.7tons
average per farm:[13.76 11.32 15.68 11.78]tons
average per season:[12.275 12.6   13.35  13.275 14.175]tons
maximum yield:16.8tons
minimum yield:10.3tons


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6,]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [18]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


In [21]:
import numpy as np
a=np.array(47)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)




0
1
2
3


In [23]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('number of dimension:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimension: 5


In [24]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [25]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[3]+arr[2])

7


In [30]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a@b
c=a*b
transposed=c.T
print(a@b)
print(c)
print(transposed)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[ 5 21]
 [12 32]]
