<a href="https://colab.research.google.com/github/pramodshetyy780-del/AI_ML_programs_PRAMOD/blob/main/quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
a[b]

array([1, 3, 5])

In [ ]:
import numpy as np
arr=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
mask=np.array([True,False,True])
arr[mask]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
a[:,[False,True]]

array([[2],
       [4],
       [6]])

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1],[2],[3]])
print(a+b)

[[1]
 [2]
 [3]]
