<a href="https://colab.research.google.com/github/pramodshetyy780-del/AI_ML_programs_PRAMOD/blob/main/statisticalfunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
rainfall=np.array([45,52,68,120,180,220,195,160,110,75,58,40])
yields=np.array([2.1,2.3,2.8,4.2,5.8,6.5,5.9,5.2,3.8,2.9,2.4,2.0])
print('===rainfal statistics===')
print(f'mean:{np.mean(rainfall):.2f}mm')
print(f'median:{np.median(rainfall):.2f}mm')
print(f'std dev:{np.std(rainfall):.2f}mm')
print(f'variance:{np.var(rainfall):.2f}')
print(f'min:{np.min(rainfall)}mm(month{np.argmin(rainfall)+1})')
print(f'max:{np.max(rainfall)}mm(month{np.argmax(rainfall)+1})')
print(f'range:{np.ptp(rainfall)}mm')
print('\n===yield statistics===')
print(f'mean:{np.mean(yields):.2f}tons/ha')
print(f'median:{np.median(yields):.2f}tons/ha')
print(f'std dev:{np.std(yields):.2f}tons/ha')
print('\n===percentiles===')
percentiles=[25,50,75,90]
rainfall_percentiles=np.percentile(rainfall,percentiles)
print(f'{rainfall_percentiles}\n')
for p,val in zip(percentiles,rainfall_percentiles):
  print(f'{p}th percentile rainfall:{val:.2f}mm')
print('\n===correlation analysis===')
correlation_matrix=np.corrcoef(rainfall,yields)
print(correlation_matrix)
correlation=correlation_matrix[0,1]
print(f'rainfall yield correlation:{correlation:.4f}')
print('interpretation:strong positive correlation'if correlation>0.7 else'moderate correlation'if correlation>0.4 else'weak correlation')
print('\n===cumulative rainfall===')
cumulative=np.cumsum(rainfall)
print(f'{cumulative}')
print('month\trainfall\tcumulative')
for month,(rain,cum) in enumerate(zip(rainfall,cumulative),1):
  print(f'{month}\t{rain}\t\t{cum}')

===rainfal statistics===
mean:110.25mm
median:92.50mm
std dev:61.24mm
variance:3750.52
min:40mm(month12)
max:220mm(month6)
range:180mm

===yield statistics===
mean:3.82tons/ha
median:3.35tons/ha
std dev:1.58tons/ha

===percentiles===
[ 56.5  92.5 165.  193.5]

25th percentile rainfall:56.50mm
50th percentile rainfall:92.50mm
75th percentile rainfall:165.00mm
90th percentile rainfall:193.50mm

===correlation analysis===
[[1.         0.99825685]
 [0.99825685 1.        ]]
rainfall yield correlation:0.9983
interpretation:strong positive correlation

===cumulative rainfall===
[  45   97  165  285  465  685  880 1040 1150 1225 1283 1323]
month	rainfall	cumulative
1	45		45
2	52		97
3	68		165
4	120		285
5	180		465
6	220		685
7	195		880
8	160		1040
9	110		1150
10	75		1225
11	58		1283
12	40		1323


In [ ]:
import numpy as np
rainfall=np.array([45,52,68,120,180,220,195,160,110,75,58,40])
yields=np.array([2.1,2.3,2.8,4.2,5.8,6.5,5.9,5.2,3.8,2.9,2.4,2.0])
print('===rainfal statistics===')
print(f'mean:{np.mean(rainfall):.2f}mm')
print(f'median:{np.median(rainfall):.2f}mm')
print(f'std dev:{np.std(rainfall):.2f}mm')
print(f'variance:{np.var(rainfall):.2f}')
print(f'min:{np.min(rainfall)}mm(month{np.argmin(rainfall)+1})')
print(f'max:{np.max(rainfall)}mm(month{np.argmax(rainfall)+1})')
print(f'range:{np.ptp(rainfall)}mm')
print('\n===yield statistics===')
print(f'mean:{np.mean(yields):.2f}tons/ha')
print(f'median:{np.median(yields):.2f}tons/ha')
print(f'std dev:{np.std(yields):.2f}tons/ha')
print('\n===percentiles===')
percentiles=[25,50,75,90]
rainfall_percentiles=np.percentile(rainfall,percentiles)
print(f'{rainfall_percentiles}\n')
for p,val in zip(percentiles,rainfall_percentiles):
  print(f'{p}th percentile rainfall:{val:.2f}mm')
print('\n===correlation analysis===')
correlation_matrix=np.corrcoef(rainfall,yields)
print(correlation_matrix)
correlation=correlation_matrix[0,1]
print(f'rainfall yield correlation:{correlation:.4f}')
print('interpretation:strong positive correlation'if correlation>0.7 else'moderate correlation'if correlation>0.4 else'weak correlation')
print('\n===cumulative rainfall===')
cumulative=np.cumsum(rainfall)
print(f'{cumulative}')
print('month\tcumulative\t')
for month,cum in enumerate((cumulative),1):
  print(f'{month}\t{cum}\t')

===rainfal statistics===
mean:110.25mm
median:92.50mm
std dev:61.24mm
variance:3750.52
min:40mm(month12)
max:220mm(month6)
range:180mm

===yield statistics===
mean:3.82tons/ha
median:3.35tons/ha
std dev:1.58tons/ha

===percentiles===
[ 56.5  92.5 165.  193.5]

25th percentile rainfall:56.50mm
50th percentile rainfall:92.50mm
75th percentile rainfall:165.00mm
90th percentile rainfall:193.50mm

===correlation analysis===
[[1.         0.99825685]
 [0.99825685 1.        ]]
rainfall yield correlation:0.9983
interpretation:strong positive correlation

===cumulative rainfall===
[  45   97  165  285  465  685  880 1040 1150 1225 1283 1323]
month	cumulative	
1	45	
2	97	
3	165	
4	285	
5	465	
6	685	
7	880	
8	1040	
9	1150	
10	1225	
11	1283	
12	1323	
